#
# Copyright 2024-2025 Ping Identity Corporation. All Rights Reserved
#
# This code is to be used exclusively in connection with Ping Identity
# Corporation software or services. Ping Identity Corporation only offers
# such software or services to legal entities who have entered into a
# binding license agreement with Ping Identity Corporation.
#
nodeDescription=PingOne Identity Match
nodeHelp=This node checks whether the user of the Ping AM exists in the PingOne platform.<br><br>\
If the user already exists in the PingOne platform, the node sets the PingOne user ID in the shared state under a key \
  named <code>pingOneUserId</code>.

tntpPingOneConfigName=PingOne Service
tntpPingOneConfigName.help=Service for PingOne, PingOne Verify, PingOne Protect *, and PingOne DaVinci API.

populationId=Population ID
populationId.help=The unique identifier for the PingOne population.<br><br>\
 If not specified, the node uses the environment's default population.

amIdentityAttribute=AM identity attribute
amIdentityAttribute.help=The attribute of the existing AM identity object that will be used to query the PingOne user. \
  If there are multiple entries with the same attribute value in the PingOne directory server, ensure that this \
  property is specific enough to retrieve only one entry.

pingIdentityAttribute=PingOne identity attribute
pingIdentityAttribute.help=The PingOne user attribute to be used for matching the AM user. If this attribute identifies \
  more than one user with the same value in the PingOne system, it will fail.

captureFailure=Capture failure
captureFailure.help=If selected, a failure is captured in shared state under a key\
  named <code>pingOneIdentityMatchFailureReason</code> for use by subsequent nodes in the journey.
