#
# Copyright 2024-2025 Ping Identity Corporation. All Rights Reserved
#
# This code is to be used exclusively in connection with Ping Identity
# Corporation software or services. Ping Identity Corporation only offers
# such software or services to legal entities who have entered into a
# binding license agreement with Ping Identity Corporation.
#

nodeDescription=PingOne Verify Completion Decision
nodeHelp=The PingOne Verify Completion Decision node determines the completion status of the end user's identity \
  verification on the PingOne platform. <br><br>\
  The node checks the previous identity verification for the end user and returns an outcome based on the \
  end user's current verification status. <br><br>\
  With a custom script, the node can evaluate any of the user's Verify Transactions and their metadata, instead \
  of just the last transaction.

tntpPingOneConfigName=PingOne Service
tntpPingOneConfigName.help=Service for PingOne, PingOne Verify, PingOne Protect *, and PingOne DaVinci API.

useFilterScript=Use a script to process Verify transactions
useScript.help=Use a custom script to filter Verify transactions. When enabled, \
  the node can evaluate any of the user's Verify transactions and their metadata, instead of just the last \
  transaction. <br><br>\
  The script's type must be: Decision Node Script.

script=Manage Verify transactions script
script.help=A custom Decision Node script that evaluates the user's Verify transactions and their metadata.

scriptInputs=Script Inputs
scriptInputs.help=A list of inputs required by the configuration script.

captureFailure=Capture failure
captureFailure.help=If selected, a failure is captured in shared state under a key \
  named <code>pingOneVerifyCompletionFailureReason</code> for use by subsequent nodes in the journey.

# Outcomes
successOutcome=Success
failureOutcome=Failure
expiredOutcome=Expired
notStartedOutcome=Not Started
notCompletedOutcome=Not Completed
