#
# Copyright 2024-2025 Ping Identity Corporation. All Rights Reserved
#
# This code is to be used exclusively in connection with Ping Identity
# Corporation software or services. Ping Identity Corporation only offers
# such software or services to legal entities who have entered into a
# binding license agreement with Ping Identity Corporation.
#
nodeDescription=PingOne Verify Evaluation
nodeHelp=The PingOne Verify Evaluation node lets administrators integrate PingOne Verify for identity verification \
  within a journey.

tntpPingOneConfigName=PingOne Service
tntpPingOneConfigName.help=Service for PingOne, PingOne Verify, PingOne Protect *, and PingOne DaVinci API.

verifyPolicyId=PingOne Verify Policy ID
verifyPolicyId.help=The ID of the Verify policy. <br><br>\
 If not specified, the node uses the environment's default Verify policy.

deliveryMethod=Verify URL Delivery Method
deliveryMethod.help=The delivery method for the Verify URL. Choose from: \
 <ul><li><code>QRCODE</code>: Display the URL as a QR code (default)</li>\
  <li><code>EMAIL</code>: Send an email containing the URL to the email address in the user's profile</li>\
  <li><code>SMS</code>: Send an SMS containing the URL to the phone number in the user's profile</li>\
  <li><code>REDIRECT</code>: Redirect the user to the Verify Web app</li>
</ul>
deliveryMethod.QRCODE=QR code
deliveryMethod.EMAIL=Email
deliveryMethod.SMS=SMS
deliveryMethod.REDIRECT=Redirect

allowDeliveryMethodSelection=Allow user to choose the URL delivery method
allowDeliveryMethodSelection.help=If enabled, prompt the user to select the URL delivery method. This does not apply \
  if the delivery method is set to <code>Redirect</code>.

deliveryMethodMessage=Delivery Method Message
deliveryMethodMessage.help=The message to display to the user allowing them to choose the delivery method to \
  receive the verify URL (QRCODE, SMS, EMAIL).
default.deliveryMethodMessage=Select a delivery method to start the identity verification process.

scanQRCodeMessage=QR Code Message
scanQRCodeMessage.help=The message with instructions to scan the QR code to begin the identity verification process.
default.scanQRCodeMessage=Scan the QR code to initiate the identity verification process.

waitingMessage=Waiting Message
waitingMessage.help=Localization overrides for the waiting message. This is a map of locale to message.
default.waitingMessage=Waiting for identity verification completion. Here is the code you will see on your device: {{verificationCode}}

redirectMessage=Redirect Message
redirectMessage.help=The message to display to the user after the identity verification process is complete and the \
  user is redirected back to the Journey.
default.redirectMessage=Click on Return to proceed.

timeout=Verify Transaction Timeout
timeout.help=The period of time (in seconds) to wait for a response to the Verify transaction. If no \
  response is received during this time the node times out and the verification process fails.

biographicMatching=Biographic Matching
biographicMatching.help=Attributes from the user profile to compare with the data extracted from the government \
  identity document provided by the client. If empty, no biographic matching verification is performed. Key is the \
  biographic matching requirement. Value is the identity attribute name. Accepted biographic matching requirement keys: \
  referenceSelfie, phone, email, given_name, family_name, name, address, and birth_date.

createPingOneUser=Create PingOne User
createPingOneUser.help=If enabled, the node will create a PingOne user if one does not already exist.<br><br>\
 If disabled, the node expects a PingOne user ID to be present in shared state.

populationId=Population ID
populationId.help=The unique identifier for the PingOne population.<br><br>\
 Used only if <code>createPingOneUser</code> is enabled. \
 If not specified, the node uses the environment's default population.

anonymizedUser=Anonymized PingOne User
anonymizedUser.help=Whether to create the anonymized PingOne user.<br><br>\
 Used only if <code>createPingOneUser</code> is enabled.

userAttributesFromSharedState=User Attributes from Shared State
userAttributesFromSharedState.help=If enabled, the node uses user attributes from shared state \
instead of retrieving them from an AM identity. This affects PingOne user creation, delivery method attributes \
(EMAIL/SMS), and biographic matching.<br><br>Typically, this option is only relevant when \
<code>createPingOneUser</code> is enabled.


amIdentityAttribute=AM identity attribute
amIdentityAttribute.help=The attribute of the existing AM identity object that will be used as the key to identify the \
 user in the PingOne directory server.<br><br>\
 Used only if <code>createPingOneUser</code> is enabled and <code>userAttributesFromSharedState</code> is disabled.

storeVerificationMetadata=Store Verification Metadata
storeVerificationMetadata.help=Store verification metadata from PingOne Verify in the shared state under a key\
  named <code>pingOneVerifyMetadata</code>.<br><br>\
  <em>Note</em>: The key is empty if the node is unable to retrieve the verification metadata from PingOne.

storeVerifiedData=Store Verified Data
storeVerifiedData.help=Store the list of verified data submitted by the user in the shared state under a key\
  named <code>pingOneVerifyVerifiedData</code>.<br><br>\
  <em>Note</em>: The key is empty if the node is unable to retrieve the verified data from PingOne.

captureFailure=Capture Failure
captureFailure.help=If selected, a failure is captured in shared state under a key \
  named <code>pingOneVerifyEvaluationFailureReason</code> for use by subsequent nodes in the journey.

#outcomes
successOutcome=Success
failureOutcome=Failure
timeoutOutcome=Time Out
