#
# Copyright 2024-2025 Ping Identity Corporation. All Rights Reserved
#
# This code is to be used exclusively in connection with Ping Identity
# Corporation software or services. Ping Identity Corporation only offers
# such software or services to legal entities who have entered into a
# binding license agreement with Ping Identity Corporation.
#
nodeDescription=PingOne Create User
nodeHelp=This node creates a user on the PingOne platform. If the user is successfully created, the node sets the \
  PingOne user ID in the shared state under a key named <code>pingOneUserId</code>.

tntpPingOneConfigName=PingOne Service
tntpPingOneConfigName.help=Service for PingOne, PingOne Verify, PingOne Protect *, and PingOne DaVinci API.

populationId=Population ID
populationId.help=The unique identifier for the PingOne population.<br><br>\
 If not specified, the node uses the environment's default population.

anonymizedUser=Anonymized user
anonymizedUser.help=Whether to create the anonymized PingOne user.

amIdentityAttribute=AM identity attribute
amIdentityAttribute.help=The attribute of the existing AM identity object that will be used as key to identity the \
  user in the PingOne directory server.

captureFailure=Capture failure
captureFailure.help=If selected, a failure is captured in shared state under a key \
  named <code>pingOneCreateUserFailureReason</code> for use by subsequent nodes in the journey.

trueOutcome=Success
falseOutcome=Failure
