#
# Copyright 2024-2025 Ping Identity Corporation. All Rights Reserved
#
# This code is to be used exclusively in connection with Ping Identity
# Corporation software or services. Ping Identity Corporation only offers
# such software or services to legal entities who have entered into a
# binding license agreement with Ping Identity Corporation.
#
nodeDescription=PingOne Delete User
nodeHelp=This node deletes a user on the PingOne platform.<br><br>\
The node gets the PingOne user ID from shared state using the <code>pingOneUserId</code> key.

tntpPingOneConfigName=PingOne Service
tntpPingOneConfigName.help=Service for PingOne, PingOne Verify, PingOne Protect *, and PingOne DaVinci API.

captureFailure=Capture failure
captureFailure.help=If selected, a failure is captured in shared state under a key \
  named <code>pingOneDeleteUserFailureReason</code> for use by subsequent nodes in the journey.

trueOutcome=Success
falseOutcome=Failure
